export const stockData = [
    {
      id:"1",
      name:"John Nichol",
      caption:"Watch more on website development and UI designs.",
      profileurl:"https://nidhi15151.github.io/social_media_website_design/images/profile-pic.png",
      posturl:"https://nidhi15151.github.io/social_media_website_design/images/feed-image-1.png",
      class:"story story1",
      u_img:"https://nidhi15151.github.io/social_media_website_design/images/member-1.png",
      u_name:"Amisha",
      storyurl:"url(https://st.github.io/social_media_website_design//images/status-1.png)",
      Storylink:"/Story1",
      storyimg:"https://nidhi15151.github.io/social_media_website_design/images/status-1.png",
    },
    {
      id:"2",
      name:"John Nichol",
      caption:"Like and share this video with friends,Ask your doubts in the comments.",
      profileurl:"https://nidhi15151.github.io/social_media_website_design/images/profile-pic.png",
      posturl:"https://nidhi15151.github.io/social_media_website_design/images/feed-image-2.png",
      class:"story story2",
      u_img:"https://nidhi15151.github.io/social_media_website_design/images/member-1.png",
      u_name:"Shruti",
      storyurl:"url(https://nidhi15151.github.io/social_media_website_design/images/status-2.png)",
      Storylink:"/Story2",
      storyimg:"https://nidhi15151.github.io/social_media_website_design/images/status-2.png",
    },

    {
      id:"3",
      name:"John Nichol ",
      caption:"Watch more on website development and UI designs.",
      profileurl:"https://nidhi15151.github.io/social_media_website_design/images/profile-pic.png",
      class:"story story3",
      storyurl:"url(https://nidhi15151.github.io/social_media_website_design/images/status-3.png)",        
      u_img:"https://nidhi15151.github.io/social_media_website_design/images/member-2.png",
      u_name:"Manisha",
      posturl:"https://nidhi15151.github.io/social_media_website_design/images/feed-image-3.png",
      Storylink:"/Story3",
      storyimg:"https://nidhi15151.github.io/social_media_website_design/images/status-3.png",
    },
    {
      id:"4",
      name:"John Nichol",
      caption:"Like and share this video with friends,Ask your doubts in the comments.",
      profileurl:"https://nidhi15151.github.io/social_media_website_design/images/profile-pic.png",
      class:"story story4",
      storyurl:"url(https://nidhi15151.github.io/social_media_website_design/images/status-4.png)",
      u_img:"https://nidhi15151.github.io/social_media_website_design/images/member-3.png",
      u_name:"Xyz",
      posturl:"https://nidhi15151.github.io/social_media_website_design/images/feed-image-4.png",
      Storylink:"/Story4",
      storyimg:"https://nidhi15151.github.io/social_media_website_design/images/status-4.png",
    },
    {
      id:"5",
      name:"John Nichol",
      caption:"Like and share this video with friends,Ask your doubts in the comments.",profileurl:"https://nidhi15151.github.io/social_media_website_design/images/member-4.png",
      profileurl:"https://nidhi15151.github.io/social_media_website_design/images/profile-pic.png",
      u_img:"https://nidhi15151.github.io/social_media_website_design/images/member-4.png",
      u_name:"Abc",
      class:"story story5",
      storyurl:"url(https://nidhi15151.github.io/social_media_website_design/images/status-5.png)",
      posturl:"https://nidhi15151.github.io/social_media_website_design/images/feed-image-5.png",
      Storylink:"/Story5",
      storyimg:"	https://nidhi15151.github.io/social_media_website_design/images/status-5.png",
    },
    
  ];
   
  localStorage.setItem("profile", JSON.stringify(stockData));

